# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartRES' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartRES

  pod 'ImageSlideshow', '~> 1.8'
  pod "YPImagePicker"
  pod "AlamofireImage"
  pod "Alamofire"
  pod "ImageSlideshow/Alamofire"
  pod "ImageSlideshow/Parse"
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'

  target 'SmartRESTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartRESUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
